### ISSUE TITLE
PermissionError: access denied

### ISSUE THREAD

**Issue by Schlunze** [shred/fritzswitch#3]
Hello,

first thank to you for this tool, i use it with octoprint for over a year now. Today i realized that someting dont work anymore. Here the error message after switching from command line:

pi@octopi:~ $ /home/pi/fritzswitch.py -u user -p password -H ip -a number -1
Traceback (most recent call last):
  File "/home/pi/fritzswitch.py", line 169, in <module>
    fha = FritzHomeAuto(args.user, args.password, host)
  File "/home/pi/fritzswitch.py", line 35, in __init__
    self.sid = self.get_sid(user, password)
  File "/home/pi/fritzswitch.py", line 56, in get_sid
    raise PermissionError('access denied')
PermissionError: access denied

The fritz.box user has "Smart Home" permission. Is it an python update issue with octopi?

Thank you in advance. 
Greetings 
Schlunze

**Comment by shred** [comment]
I don't think it's related to a Python update.

I have just tested the script with the latest Python 3.9.6 against a FritzBox 7590 with the latest firmware 07.27, and with a dedicated user that has only "Smart Home" permissions. It was working fine. :slightly_smiling_face: 

The error says that fritzswitch could not create a session with the FritzBox, so my guess is that something in the FritzBox configuration might have changed. Can you try a different FritzBox user for a test? Or can you just set a fresh password for your smart home FritzBox user? (I guess you already have checked the permissions.)

**Comment by Schlunze** [comment]
Hi, 
looks like i messed up something. I have updated octoprint and after that it was python2 :)

octoprint 
`python --version
Python 2.7.16`
FRITZ!OS: 07.27
tested a new user without success...
On another machine with Python 3.9.5 it works like expected.

After upgrading octoprint to python 3 it works like expected.
Sorry for disturbing and again thank you for this script.

Greetings

**Comment by shred** [comment]
No problem at all. I'm glad that there was an easy solution. :smile:
